name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache do Cypress
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-

      - name: Instalar dependências
        run: npm ci  

      - name: Verificar estrutura do projeto (debug)
        run: ls -R  

      - name: Instalar Cypress manualmente
        run: npx cypress install

      - name: Verificar instalação do Cypress
        run: npx cypress verify

      - name: Rodar testes do Cypress (headless) com Mochawesome
        run: npx cypress run --headless --reporter mochawesome --spec 'cypress/e2e/features/**/*.feature'

      - name: Verificar relatório JSON gerado
        run: ls -lh cypress/reports/ || echo "Relatório não encontrado!"

      - name: Mesclar relatórios do Mochawesome
        run: npm install mochawesome-merge mochawesome-report-generator 
       
      - name: Gerar relatório JSON mesclado
        run: npx mochawesome-merge cypress/reports/*.json > cypress/reports/merged-report.json

      - name: Gerar relatório em PDF
        if: always()
        run: |
          npm install pdfkit  # Instalar dependências para geração do PDF
          node merge_report.js  # Executar script para mesclar os relatórios (se necessário)
          node gerar_relatorio.js  # Executar script para gerar o PDF

      - name: Upload de screenshots e vídeos
        if: always()  
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: |
            cypress/screenshots
            cypress/videos
            cypress/reports
      
      - name: Upload do relatório PDF
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-pipeline
          path: relatorio_tests.pdf