name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.17.0' # Use a versão do Node.js que seu projeto precisa

    - name: Cache Cypress binary
      uses: actions/cache@v3
      id: cypress-cache
      with:
        path: ~/.cache/Cypress
        key: cypress-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          cypress-${{ runner.os }}-

    - name: Install dependencies
      run: npm install

    - name: Install Cypress binary (if not cached)
      if: steps.cypress-cache.outputs.cache-hit != 'true'
      run: npx cypress install

    - name: Verify Cypress installation
      run: npx cypress verify

    - name: List cached Cypress binary
      run: ls -la ~/.cache/Cypress

    - name: Check Cypress version
      run: npx cypress --version

    - name: Run Cypress tests
      run: npx cypress run
